### PR TITLE
ID-99 API Tests

### PR DESCRIPTION
**Pull request by LachPawel**
# ContentfulApi and filterData functions tested

TODO:

- fix redundancy in the code
- add FormCarry API tests

JIRA: [https://master-program-ikss-d.atlassian.net/secure/RapidBoard.jspa?rapidView=1&modal=detail&selectedIssue=ID-99](url)

### CODE REVIEW

**Review by BartekFo — CHANGES_REQUESTED** [review]
Everything work nice. Good job with this test. Impressive. One thing that we talked on our meet need to be changed 👌

**Review by BartekFo — APPROVED** [review]
LGTM

**Review by MilyB33 — CHANGES_REQUESTED** [review]
Tests looks good. Nice work :grinning: . Only one thing to discuss.

**Review by MilyB33 — APPROVED** [review]

**Review by LachPawel — COMMENTED** [review]
fix: tests on github won't crash again

**Review by AdamKopf — APPROVED** [review]

**Pull request merged**
